### ISSUE TITLE
Cannot get property DirectionProperty [...] as it does not exist in Block{minecraft:void_air}

### ISSUE THREAD

**Issue by ghost** [McJtyMods/restrictions#20]
Relaying https://github.com/AllTheMods/ATM-10/issues/1451
ATM10 version 2.6, NeoForge version 21.1.90, Restrictions version 1.21-7.0.2

Players using the restrictions attractor, crashing on interaction with air.

Crash Log
https://gist.github.com/Silicat-git/eee1f2cc8cf3ebc8553427daaf64af49

Latest.Log
https://gist.github.com/Silicat-git/d8e9039a823b89adc613c69cafe5fd24

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Weird. I cannot reproduce this. Can you tell me exactly how they were doing this?

**Comment by ghost** [comment]
I am trying to reproduce it, have also asked the person to come here.
Also have another with the same problem.
https://github.com/AllTheMods/ATM-10/issues/1256
Lets see if [@Nikol](https://github.com/NikolaMC) perhaps knows more, though its been a while ill admit

**Comment by ghost** [comment]
So i managed to crash too
was doing something completely unrelated when setups that i had been teleporting around to previously without issue, now crashes me
Crash log: https://mclo.gs/37yr20p
Video of crash (does not contain the attractor setup): 

https://github.com/user-attachments/assets/2a75c5f9-049b-4fe3-a03a-d74e0145b216

There was a game restart between when i was successfully teleporting and when it crashes me
The chunks with the attractor setup does not get unloaded by me doing this teleport due to force loading, and the teleport was quite far away in the same dimension.
Image of the attractor setup that crashes:
![image](https://github.com/user-attachments/assets/140545be-a253-4f3f-a0c2-80c6be308820)
During the test there was a wandering trader in the setup, trader was removed for visibility

**Comment by Silicat-git** [comment]
We removed the attractor since then, but I was able to reproduce it consistently by teleporting away from a powered attractor.
The chunks teleporting from and to are both force loaded.


https://github.com/user-attachments/assets/a10a2063-d9fc-4f94-9a90-4777c24eac48

**Comment by McJty** [comment]
I cannot reproduce it but I do know how to fix it. I'll do that

**Comment by McJty** [comment]
Fixed in version 7.0.3

**Comment by pietro-lopes** [comment]
Can you release? We are still having this issue.

Edit:

https://www.curseforge.com/minecraft/mc-mods/restrictions/files/6009445
Please mark as Neoforge

**Comment by McJty** [comment]
Oops, indeed forgot to mark. Should be fixed now
